api_version = "2025-07"
uid = "55b363fe-46d7-83d0-9d54-37d6dbe2d57557316b6e"

[[extensions]]
name = "Click & Collect - Order Actions"
handle = "click-collect-admin"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/OrderAction.tsx"
target = "admin.order-details.action.render"

[[extensions.targeting]]
module = "./src/OrderBlock.tsx"
target = "admin.order-details.block.render"

[extensions.capabilities]
network_access = true
api_access = true
