api_version = "2025-07"
uid = "88700fb1-8ff3-10ea-4e39-2aad4b3da1c155b4743b"

[[extensions]]
type = "function"
name = "Click and Collect - Hide Shipping"
handle = "click-collect-delivery-customization"
api_type = "delivery_customization"

[[extensions.targeting]]
module = "./src/index.js"
target = "purchase.delivery-customization.run"
input_query = "./src/run.graphql"
