api_version = "2025-07"
uid = "b45554fe-ea59-553d-69cb-caa1fc337815617fc945"

[[extensions]]
name = "Click & Collect — Pickup Selector"
handle = "click-collect-checkout"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/Checkout.tsx"
target = "purchase.checkout.delivery-address.render-before"

[[extensions.targeting]]
module = "./src/ThankYou.tsx"
target = "purchase.thank-you.block.render"

[extensions.capabilities]
network_access = true
