api_version = "2025-07"
uid = "c227835f-f48a-eb31-a75c-e7c47468cdc47d3ef815"

[[extensions]]
name = "Click & Collect - Order Block"
handle = "click-collect-order-block"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/OrderBlock.tsx"
target = "admin.order-details.block.render"

[extensions.capabilities]
network_access = true
api_access = true
